### ISSUE TITLE
Tests require Elasticsearch to be running if `api.targets.auto_discover` is set to true

### ISSUE THREAD

**Issue by orangejulius** [pelias/api#1419]
With this value set in `pelias.json`, running `npm test` will hang and print errors:

```
$ npm test

> pelias-api@0.0.0-development test /home/julian/repos/pelias/api
> npm run unit


> pelias-api@0.0.0-development unit /home/julian/repos/pelias/api
> ./bin/units


  ..................Elasticsearch ERROR: 2020-04-07T15:49:03Z
  Error: Request error, retrying
  POST http://localhost:9200/_search?request_cache=true&timeout=10s => connect ECONNREFUSED 127.0.0.1:9200
      at Log.error (/home/julian/repos/pelias/api/node_modules/elasticsearch/src/lib/log.js:239:56)
      at checkRespForFailure (/home/julian/repos/pelias/api/node_modules/elasticsearch/src/lib/transport.js:298:18)
      at HttpConnector.<anonymous> (/home/julian/repos/pelias/api/node_modules/elasticsearch/src/lib/connectors/http.js:171:7)
      at ClientRequest.wrapper (/home/julian/repos/pelias/api/node_modules/lodash/lodash.js:4929:19)
      at ClientRequest.emit (events.js:311:20)
      at Socket.socketErrorListener (_http_client.js:426:9)
      at Socket.emit (events.js:311:20)
      at emitErrorNT (internal/streams/destroy.js:92:8)
      at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)

Elasticsearch WARNING: 2020-04-07T15:49:03Z
  Unable to revive connection: http://localhost:9200/

Elasticsearch WARNING: 2020-04-07T15:49:03Z
  No living connections

{"message":"No Living connections","stack":"Error: No Living connections\n    at sendReqWithConnection (/home/julian/repos/pelias/api/node_modules/elasticsearch/src/lib/transport.js:266:15)\n    at next (/home/julian/repos/pelias/api/node_modules/elasticsearch/src/lib/connection_pool.js:243:7)\n    at processTicksAndRejections (internal/process/task_queues.js:79:11)","level":"error","label":"api:type_mapping_discovery","timestamp":"2020-04-07T15:49:03.280Z"}
```

**Comment by orangejulius** [comment]
Since https://github.com/pelias/api/pull/1431 from last year, we run the unit tests with a specific `pelias.json` file from the test directory.

Currently, that [file is empty](https://github.com/pelias/api/blob/6a7751f35882698eb885b93635656ec0c2941633/test/pelias-config-empty.json#L1), but we could easily make it included `targets.auto_discover=false`, which would allow us to merge https://github.com/pelias/config/pull/127.

So it seems like we could end the current situation where we'd prefer `targets.auto_discover` to default to true, but aren't doing so simply to get the unit tests in this repository to pass.

In the future, we might find that we want to add some new unit tests to cover the auto discover functionality, and those might need `targets.auto_discover` set to true in their individual tests, but that would be a task for another day.

**Comment by orangejulius** [comment]
It took a little work, but the changes in https://github.com/pelias/api/pull/1521 should allow us to finally resolve this!
