### ISSUE TITLE
TypeError: Object.values(...).flat is not a function

### ISSUE THREAD

**Issue by bdmapman** [pelias/api#1661]
Hello, I have built the Pelias locally. After that I populated data using, Geonames, Placeholder, Whosonfirst, Openstreetmaps and CSV. Whenever I am calling forward or reverse geocoding with a paramater  `sources` or `layers` it is returning the following error

```
TypeError: Object.values(...).flat is not a function
    at allTargets (/opt/tools/pelias/api/sanitizer/_targets.js:18:47)
    at Object._sanitize [as sanitize] (/opt/tools/pelias/api/sanitizer/_targets.js:72:27)
    at sanitize (/opt/tools/pelias/api/sanitizer/sanitizeAll.js:40:32)
    at Object.runAllChecks (/opt/tools/pelias/api/sanitizer/sanitizeAll.js:95:3)
    at /opt/tools/pelias/api/sanitizer/reverse.js:45:17
    at Layer.handle [as handle_request] (/opt/tools/pelias/api/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/tools/pelias/api/node_modules/express/lib/router/index.js:328:13)
    at /opt/tools/pelias/api/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/opt/tools/pelias/api/node_modules/express/lib/router/index.js:346:12)
    at next (/opt/tools/pelias/api/node_modules/express/lib/router/index.js:280:10)
```

Is it a bug or I am missing something?

**Comment by orangejulius** [comment]
I'm guessing this is due to using an old version of Node.js: MDN shows that `Array.flat` was [added in Node.js 11](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat).

If you can still reproduce this feel free to reopen, otherwise I'm closing this to keep our issue tracker clean 🙏
