### ISSUE TITLE
Unexpected `sources` type causes an exception

### ISSUE THREAD

**Issue by dianashk** [pelias/api#233]
If you specify the wrong `sources` value, you'll get this:

```
{
error: "Cannot read property 'types' of undefined"
}
```

logs show:

```
2015-09-10_15:11:42.12987 2015-09-10T15:11:42.129Z - error: [middleware-500] Error: `TypeError: Cannot read property 'types' of undefined`. Stack trace: `TypeError: Cannot read property 'types' of undefined
2015-09-10_15:11:42.13000     at middleware (/srv/www/api/releases/20150909163117/middleware/_types.js:11:37)
2015-09-10_15:11:42.13006     at Layer.handle [as handle_request] (/srv/www/api/releases/20150909163117/node_modules/express/lib/router/layer.js:95:5)
2015-09-10_15:11:42.13010     at trim_prefix (/srv/www/api/releases/20150909163117/node_modules/express/lib/router/index.js:312:13)
2015-09-10_15:11:42.13014     at /srv/www/api/releases/20150909163117/node_modules/express/lib/router/index.js:280:7
2015-09-10_15:11:42.13017     at Function.process_params (/srv/www/api/releases/20150909163117/node_modules/express/lib/router/index.js:330:12)
2015-09-10_15:11:42.13020     at next (/srv/www/api/releases/20150909163117/node_modules/express/lib/router/index.js:271:10)
2015-09-10_15:11:42.13023     at /srv/www/api/releases/20150909163117/sanitiser/search.js:25:5
2015-09-10_15:11:42.13026     at sanitize (/srv/www/api/releases/20150909163117/sanitiser/_sanitize.js:8:14)
2015-09-10_15:11:42.13029     at sanitize (/srv/www/api/releases/20150909163117/sanitiser/search.js:12:36)
2015-09-10_15:11:42.13032     at module.exports.middleware (/srv/www/api/releases/20150909163117/sanitiser/search.js:19:3)`.
```

Add property error handling and an error message that lists possible values.

**Comment by orangejulius** [comment]
Oh good catch. If there's time today I'll try to pair on this with Steve today
