### ISSUE TITLE
Cannot read property 'number' of undefined

### ISSUE THREAD

**Issue by jthi3rry** [pelias/api#297]
Hi there,

After releasing ae50201c271e0dfaffc65c106b77a78d8a948ba9 (PR #291), I get the following on the `search` and `autocomplete` endpoints (`reverse` still works):

```
{
  error: "Cannot read property 'number' of undefined"
}
```

I tried releasing all revisions one at a time from the one I had up to this one, and this is when it breaks.

Here's the stack trace from the logs:
```
2015-09-22T22:26:57.264Z - error: [middleware-500] Error: `TypeError: Cannot read property 'number' of undefined`. Stack trace: `TypeError: Cannot read property 'number' of undefined
    at checkQueryType (/home/pelias/pelias-api/middleware/confidenceScore.js:142:13)
    at computeConfidenceScore (/home/pelias/pelias-api/middleware/confidenceScore.js:68:21)
    at Array.map (native)
    at computeScores (/home/pelias/pelias-api/middleware/confidenceScore.js:36:23)
    at Layer.handle [as handle_request] (/home/pelias/pelias-api/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pelias/pelias-api/node_modules/express/lib/router/index.js:312:13)
    at /home/pelias/pelias-api/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/pelias/pelias-api/node_modules/express/lib/router/index.js:330:12)
    at next (/home/pelias/pelias-api/node_modules/express/lib/router/index.js:271:10)
    at computeDistances (/home/pelias/pelias-api/middleware/distance.js:24:12)`.
```

**Comment by riordan** [comment]
Thanks for flagging this. We're on it!

On Tue, Sep 22, 2015 at 6:28 PM, Thierry Jossermoz <notifications@github.com
> wrote:

> Hi there,
>
> After releasing ae50201
> <https://github.com/pelias/api/commit/ae50201c271e0dfaffc65c106b77a78d8a948ba9>
> (PR #291 <https://github.com/pelias/api/pull/291>), I get the following
> on the search and autocomplete endpoints (reverse still works):
>
> {
>   error: "Cannot read property 'number' of undefined"
> }
>
> I tried releasing all revisions one at a time from the one I had up to
> this one, and this is when it breaks.
>
> Here's the stack trace from the logs:
>
> 2015-09-22T22:26:57.264Z - error: [middleware-500] Error: `TypeError: Cannot read property 'number' of undefined`. Stack trace: `TypeError: Cannot read property 'number' of undefined
>     at checkQueryType (/home/pelias/pelias-api/middleware/confidenceScore.js:142:13)
>     at computeConfidenceScore (/home/pelias/pelias-api/middleware/confidenceScore.js:68:21)
>     at Array.map (native)
>     at computeScores (/home/pelias/pelias-api/middleware/confidenceScore.js:36:23)
>     at Layer.handle [as handle_request] (/home/pelias/pelias-api/node_modules/express/lib/router/layer.js:95:5)
>     at trim_prefix (/home/pelias/pelias-api/node_modules/express/lib/router/index.js:312:13)
>     at /home/pelias/pelias-api/node_modules/express/lib/router/index.js:280:7
>     at Function.process_params (/home/pelias/pelias-api/node_modules/express/lib/router/index.js:330:12)
>     at next (/home/pelias/pelias-api/node_modules/express/lib/router/index.js:271:10)
>     at computeDistances (/home/pelias/pelias-api/middleware/distance.js:24:12)`.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pelias/api/issues/297>.
>



-- 
David Riordan | Product Manager - Search | dave.riordan@mapzen.com |
@riordan <https://twitter.com/riordan> | gpg 235D9DC95EF6277C
<https://keybase.io/riordan>
Mapzen | https://mapzen.com | @mapzen <https://twitter.com/search>
