### ISSUE TITLE
Maximum call stack size exceeded with NodeJS 4

### ISSUE THREAD

**Issue by BenJoyenConseil** [pelias/api#361]
I build the project with NodeJS 4.2.1 version.
When I run it with node index.js :

RangeError: Maximum call stack size exceeded
    at Log.listenerCount (/root/api/node_modules/pelias-esclient/node_modules/elasticsearch/src/lib/log.js:65:40)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/root/api/node_modules/pelias-esclient/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/root/api/node_modules/pelias-esclient/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/root/api/node_modules/pelias-esclient/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/root/api/node_modules/pelias-esclient/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
(node) _writableState.buffer is deprecated. Use _writableState.getBuffer instead.

It appears that a version of Node higher than 0.10.40 will cause bad behaviour : 
https://github.com/elastic/elasticsearch-js/blob/1.4/src/lib/log.js

Log.prototype.listenerCount = function (event) {
  // compatability for node < 0.10
  if (EventEmitter.listenerCount) {
    return EventEmitter.listenerCount(this, event);
  } else {
    return this.listeners(event).length;
  }
};

The elasticsearch package dependency from the pelias-esclient module should be updated to the latest version (actually 8.2.0) to resolve this issue :
https://github.com/elastic/elasticsearch-js/blob/9.0/src/lib/log.js

Log.prototype.listenerCount = function (event) {
  // node >= 3.0 supports EE#listenerCount()
  if (EventEmitter.prototype.listenerCount) {
    return EventEmitter.prototype.listenerCount.call(this, event);
  }

  // compatability for node < 0.10
  if (EventEmitter.listenerCount) {
    return EventEmitter.listenerCount(this, event);
  }

  return this.listeners(event).length;
};

As a workaround, you can downgrade NodeJS version to 0.10.40, and rebuild the projet with npm. Or change the elasticsearch version into the package.json file from pelias-esclient project.

PS : openstreetmap importer and other project using pelias-esclient should have the same issue

**Comment by orangejulius** [comment]
Hey @BenJoyenConseil,
Thanks so much for reporting this. We have it on our roadmap to get everything working with Node 4. If upgrading some dependencies worked for you, we would love pull requests to help us along. We will do some testing on our end, and don't worry if you don't get to every package.

**Comment by orangejulius** [comment]
I think we've gotten 4.x support taken care of, if there are any more issues please don't hesitate to reopen or report a new issue.
