### ISSUE TITLE
npm run docs fail

### ISSUE THREAD

**Issue by armadillabs** [pelias/api#395]
Hi there:

I am trying to generate the API docs, and errors when trying to run `npm run docs`.

Here is the stack trace and logs:

```
> pelias-api@2.2.0 docs /Users/pma/Palantir/repo/garnet/pelias-api
> rm -r docs; cd test/ciao; node ../../node_modules/ciao/bin/ciao -c ../ciao.json . -d ../../docs

rm: docs: No such file or directory
 /Users/pma/Palantir/repo/garnet/pelias-api/node_modules/ciao/bin/ciao:42
  if( err ) throw new Error( err );
            ^

Error: Unexpected end of input
  at ciao (/Users/pma/Palantir/repo/garnet/pelias-api/node_modules/ciao/bin/ciao:42:19)
  at RequestChain.done (/Users/pma/Palantir/repo/garnet/pelias-api/node_modules/ciao/lib/Script.coffee:14:12)
  at /Users/pma/Palantir/repo/garnet/pelias-api/node_modules/ciao/lib/RequestChain.coffee:81:17
  at /Users/pma/Palantir/repo/garnet/pelias-api/node_modules/ciao/node_modules/async/lib/async.js:726:13
  at /Users/pma/Palantir/repo/garnet/pelias-api/node_modules/ciao/node_modules/async/lib/async.js:52:16
  at done (/Users/pma/Palantir/repo/garnet/pelias-api/node_modules/ciao/node_modules/async/lib/async.js:241:17)
  at /Users/pma/Palantir/repo/garnet/pelias-api/node_modules/ciao/node_modules/async/lib/async.js:44:16
  at /Users/pma/Palantir/repo/garnet/pelias-api/node_modules/ciao/node_modules/async/lib/async.js:723:17
  at /Users/pma/Palantir/repo/garnet/pelias-api/node_modules/ciao/node_modules/async/lib/async.js:167:37
  at Process.<anonymous> (/Users/pma/Palantir/repo/garnet/pelias-api/node_modules/ciao/lib/RequestChain.coffee:72:18)
  at emitMany (events.js:108:13)
  at Process.emit (events.js:182:7)
  at ChildProcess.<anonymous> (/Users/pma/Palantir/repo/garnet/pelias-api/node_modules/ciao/lib/Process.coffee:32:8)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at maybeClose (internal/child_process.js:821:16)
  at Socket.<anonymous> (internal/child_process.js:319:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:469:12)


npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.4.0/bin/node" "/usr/local/bin/npm" "run" "docs"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! pelias-api@2.2.0 docs: `rm -r docs; cd test/ciao; node ../../node_modules/ciao/bin/ciao -c ../ciao.json . -d ../../docs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pelias-api@2.2.0 docs script 'rm -r docs; cd test/ciao; node ../../node_modules/ciao/bin/ciao -c ../ciao.json . -d ../../docs'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pelias-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -r docs; cd test/ciao; node ../../node_modules/ciao/bin/ciao -c ../ciao.json . -d ../../docs
npm ERR! You can get their info via:
npm ERR!     npm owner ls pelias-api
npm ERR! There is likely additional logging output above.
```

**Comment by orangejulius** [comment]
Hey @armadillabs,
Thanks for reporting this, it definitely slipped under our radar. Unfortunately after digging into things a bit, it looks like there are quite a few things that one has to do before the docs can be generated successfully. Some of them I've put into #403, but in addition you will have to set up enough of a Pelias instance that it has at least some data for each of our Quattroshapes, Geonames, Openstreetmap, and Openaddresses importers, or some of the tests that are used to generate the docs will fail.

So, in order to save you from that task, I've done it on my machine and attached the docs. Here you go!
[pelias-docs.zip](https://github.com/pelias/api/files/116305/pelias-docs.zip)

If you have any other trouble with the docs please let us know. Otherwise we'll probably close this ticket soon to help us keep track of things better. Enjoy!

**Comment by armadillabs** [comment]
Thanks @orangejulius!

**Comment by orangejulius** [comment]
Oh and by the way, these docs are auto-generated by [ciao](https://github.com/missinglink/ciao). Let us know how useful they are, but we have more official docs [here](https://mapzen.com/documentation/search/)
