### ISSUE TITLE
Cannot read property of undefined

### ISSUE THREAD

**Issue by curiousc0w** [pelias/api#498]
I have a Pelias instance running without the use of vagrant. I am using node v0.12.0 for this and so far I've done an Australia countrywide OA import and Quattroshapes import without any major issues. I can query addresses and receive results,  ie. (search?text=main+street). Although when I try to query a place name, for example, I receive the following error:

```
$ curl 'http://localhost:3100/v1/search?text=canada' | jq '.'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    57  100    57    0     0    428      0 --:--:-- --:--:-- --:--:--   431

{
  "error": "Cannot read property 'country_a' of undefined"
}
```

The api terminal response:
```

2016-04-13T04:06:44.893Z - info: [api] 127.0.0.1 - - [13/Apr/2016:04:06:44 +0000] "GET /v1/search?text=canada HTTP/1.1" 500 57
2016-04-13T04:07:32.119Z - info: [api] Ignoring address parser output, regions only
2016-04-13T04:07:32.120Z - info: [api:controller:search] [req] endpoint=/v1/search text=canada, size=10, private=false, querySize=20
2016-04-13T04:07:32.243Z - info: [api] [dupe] query=canada, hit=Canada
2016-04-13T04:07:32.243Z - info: [api] [dupe] query=canada, hit=Canadian
2016-04-13T04:07:32.245Z - error: [middleware-500] Error: `TypeError: Cannot read property 'country_a' of undefined`. Stack trace: `TypeError: Cannot read property 'country_a' of undefined
    at /home/user/pelias/api/middleware/localNamingConventions.js:27:28
    at Array.filter (native)
    at applyLocalNamingConventions (/home/user/pelias/api/middleware/localNamingConventions.js:25:12)
    at Layer.handle [as handle_request] (/home/user/pelias/api/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/user/pelias/api/node_modules/express/lib/router/index.js:312:13)
    at /home/user/pelias/api/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/user/pelias/api/node_modules/express/lib/router/index.js:330:12)
    at next (/home/user/pelias/api/node_modules/express/lib/router/index.js:271:10)
    at dedupeResults (/home/user/pelias/api/middleware/dedupe.js:31:3)
    at Layer.handle [as handle_request] (/home/user/pelias/api/node_modules/express/lib/router/layer.js:95:5)`.
2016-04-13T04:07:32.248Z - info: [api] 127.0.0.1 - - [13/Apr/2016:04:07:32 +0000] "GET /v1/search?text=canada HTTP/1.1" 500 57
```

I've noticed that the production branches have been updated recently. Is this error a result of that? If so, is there a branch that can be used that isn't being updated and isn't currently using WOF?

**Comment by orangejulius** [comment]
Hey @curiousc0w,
Thanks for finding this. It's definitely a bug. I put a pull request in (#499) to fix this, let me know if this prevents the error from happening for you.

**Comment by orangejulius** [comment]
And regarding the production branches update, yes we did just update them with Who's on First. We don't plan to support Quattroshapes for admin lookup ever again, as Quattroshapes is no longer being maintained and the data is getting more and more out of date. Who's on First has all the Quattroshapes data, as well as lots of other data, and is being [frequently updated](https://github.com/whosonfirst/whosonfirst-data/commits/master).
