### ISSUE TITLE
NPM start fails on Windows

### ISSUE THREAD

**Issue by mohitgoyal201617** [pelias/api#547]
Hi,

I am trying to run api after setting up pelias/openstreetmap but getting below error while running npm start

```
cat npm-debug.log
-------------------------------------------
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start',
1 verbose cli   '-verbose' ]
2 info using npm@2.15.1
3 info using node@v4.4.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart pelias-api@2.2.0
6 info start pelias-api@2.2.0
7 verbose unsafe-perm in lifecycle true
8 info pelias-api@2.2.0 Failed to exec start script
9 verbose stack Error: pelias-api@2.2.0 start: `node index.js`
9 verbose stack Exit status 4294967295
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid pelias-api@2.2.0
11 verbose cwd E:\pelias_project_setup\api
12 error Windows_NT 6.1.7601
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start" "-verbose"
14 error node v4.4.4
15 error npm  v2.15.1
16 error code ELIFECYCLE
17 error pelias-api@2.2.0 start: `node index.js`
17 error Exit status 4294967295
18 error Failed at the pelias-api@2.2.0 start script 'node index.js'.
18 error This is most likely a problem with the pelias-api package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node index.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs pelias-api
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls pelias-api
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by orangejulius** [comment]
Hi @mohitgoyal201617,
I don't think we've ever run the OSM importer on Windows. Perhaps others have, but we will need some time to look into it. I'll try to see if I can reproduce the problem next week. Thanks for reporting this! :smile:
