### ISSUE TITLE
Error running Ciao tests with Node.js 6

### ISSUE THREAD

**Issue by orangejulius** [pelias/api#642]
```
julian@julian-mapzen ~/repos/pelias/api $ npm run ciao

> pelias-api@0.0.0-semantic-release ciao /home/julian/repos/pelias/api
> node node_modules/ciao/bin/ciao -c test/ciao.json test/ciao

 /home/julian/repos/pelias/api/node_modules/ciao/bin/ciao:42
  if( err ) throw new Error( err );
            ^

Error: Unexpected end of JSON input
  at ciao (/home/julian/repos/pelias/api/node_modules/ciao/bin/ciao:42:19)
  at RequestChain.done (/home/julian/repos/pelias/api/node_modules/ciao/lib/Script.coffee:14:12)
  at /home/julian/repos/pelias/api/node_modules/ciao/lib/RequestChain.coffee:81:17
  at /home/julian/repos/pelias/api/node_modules/ciao/node_modules/async/lib/async.js:726:13
  at /home/julian/repos/pelias/api/node_modules/ciao/node_modules/async/lib/async.js:52:16
  at done (/home/julian/repos/pelias/api/node_modules/ciao/node_modules/async/lib/async.js:241:17)
  at /home/julian/repos/pelias/api/node_modules/ciao/node_modules/async/lib/async.js:44:16
  at /home/julian/repos/pelias/api/node_modules/ciao/node_modules/async/lib/async.js:723:17
  at /home/julian/repos/pelias/api/node_modules/ciao/node_modules/async/lib/async.js:167:37
  at Process.<anonymous> (/home/julian/repos/pelias/api/node_modules/ciao/lib/RequestChain.coffee:72:18)
  at emitMany (events.js:127:13)
  at Process.emit (events.js:201:7)
  at ChildProcess.<anonymous> (/home/julian/repos/pelias/api/node_modules/ciao/lib/Process.coffee:32:8)
  at emitTwo (events.js:106:13)
  at ChildProcess.emit (events.js:191:7)
  at maybeClose (internal/child_process.js:852:16)
  at Socket.<anonymous> (internal/child_process.js:323:11)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at Pipe._handle.close [as _onclose] (net.js:492:12)


npm ERR! Linux 4.2.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/home/julian/bin/npm" "run" "ciao"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! pelias-api@0.0.0-semantic-release ciao: `node node_modules/ciao/bin/ciao -c test/ciao.json test/ciao`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pelias-api@0.0.0-semantic-release ciao script 'node node_modules/ciao/bin/ciao -c test/ciao.json test/ciao'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pelias-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/ciao/bin/ciao -c test/ciao.json test/ciao
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pelias-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pelias-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/julian/repos/pelias/api/npm-debug.log
julian@julian-mapzen ~/repos/pelias/api $ node -v
v6.3.1
julian@julian-mapzen ~/repos/pelias/api $ npm -v
3.10.3
```

I tried digging into the code a bit, but couldn't figure out where the error was being generated. (My coffeescript is very rusty). This is on master with no changes and a freshly installed set of node_modules. @missinglink any idea?

**Comment by dianashk** [comment]
Not getting this error. Could it be all better since #639? @orangejulius, please confirm.

**Comment by orangejulius** [comment]
Nope, #639 doesn't fix this, in fact it was when trying to test #639 that I discovered this problem.

**Comment by missinglink** [comment]
I wasn't able to reproduce this, so I'm guessing it's an environment-specific bug.

```bash
peter: .../pelias/api (master)$ git log -1
commit b7ecd76a65cb3176bddfeff35dfef5ef2cdbc9da
Merge: 6f09259 50475c6
Author: Diana Shkolnikov <diana@mapzen.com>
Date:   Mon Aug 29 11:17:27 2016 -0400

    Merge pull request #639 from pmezard/update-test-ciao-layers
    
    test/ciao: update valid layers list in reference output
```

```bash
peter: .../pelias/api (master)$ npm run ciao

> pelias-api@0.0.0-semantic-release ciao /var/www/pelias/api
> node node_modules/ciao/bin/ciao -c test/ciao.json test/ciao

 .........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

 Time: 81.10 seconds
 Tests: 585, Errors: 0
```

```bash
peter: .../pelias/api (master)$ node --version
v4.4.7
```

**Comment by missinglink** [comment]
can you please confirm the `coffee-script` module is loading correctly on your system?

```bash
peter: .../pelias/api (master)$ cd node_modules/ciao/

peter: .../node_modules/ciao (master)$ node
> require('coffee-script/register')
{}

> require('coffee-script')
{ VERSION: '1.10.0',
  FILE_EXTENSIONS: [ '.coffee', '.litcoffee', '.coffee.md' ],
  helpers: 
   { starts: [Function],
     ends: [Function],
     repeat: [Function],
     compact: [Function],
     count: [Function],
     merge: [Function],
     extend: [Function],
     flatten: [Function],
     del: [Function],
     some: [Function: some],
     invertLiterate: [Function],
     addLocationDataFn: [Function],
     locationDataToString: [Function],
     baseFileName: [Function],
     isCoffee: [Function],
     isLiterate: [Function],
     throwSyntaxError: [Function],
     updateSyntaxError: [Function],
     nameWhitespaceCharacter: [Function] },
  compile: [Function],
  tokens: [Function],
  nodes: [Function],
  run: [Function],
  eval: [Function],
  register: [Function],
  _compileFile: [Function] }
> 
```

**Comment by orangejulius** [comment]
Looks right, I get exactly the same output

**Comment by orangejulius** [comment]
Ah, this makes sense. It works for me with node 4, but not node 6

**Comment by missinglink** [comment]
Odd bug, I'll have a look at it, maybe there is something different with the way `require()` extensions are loaded in 6 which causes coffee script to have issues.

I may also be solvable by upgrading the coffee script dependency in ciao

**Comment by rowanwins** [comment]
Gday @missinglink 

Just wondering if there is any update on this? I'm trying to run the ciao tests and am getting something like
````
> npm run ciao

> pelias-api@0.0.0-semantic-release ciao C:\Sourcetree\pelias-api
> node node_modules/ciao/bin/ciao -c test/ciao.json test/ciao

 ⚠  WARNING: Skipping file, no request section found in: test/ciao/404.coffee
 ⚠  WARNING: Skipping file, no request section found in: test/ciao/index.coffee
 ⚠  WARNING: Skipping file, no request section found in: test/ciao\search/address_parsing.coffee
````
The error list goes on for every file in the ciao directory. I ran the ciao import for the sample data and that appeared to work.

Im on node 6.4.0 and also on a windows machine....

Cheers,
Rowan

**Comment by missinglink** [comment]
kia ora @rowanwins 

I will have a look in to this when I get some free cycles, in the mean time I can confirm it runs on node 4.x (which is our recommended node version for all pelias modules).

**Comment by missinglink** [comment]
@rowanwins would you be able to try this branch and see if that works?

https://github.com/missinglink/ciao/pull/53

you can give it a go like this
```bash
rm -rf node_modules/ciao;
git clone https://github.com/missinglink/ciao.git node_modules/ciao;
cd node_modules/ciao;
git fetch;
git checkout sync;
npm install;
cd ../../;

npm run ciao;
```

**Comment by orangejulius** [comment]
I believe this particular issue was fixed a while ago. 🎉 

`ciao` definitely works as of https://github.com/pelias/api/pull/1232. 💯 

If anyone is having `ciao` issues please open a new issue here or in the ciao repo itself.
