### ISSUE TITLE
Api won't work with libpostal as textAnalyzer

### ISSUE THREAD

**Issue by kradem** [pelias/api#847]
My pelias.api service is working fine both for master and production branches as long if there's no textAnalyzer section in `pelias.json` configuration file.

If I put it like this:

```
    "api": {
        "textAnalyzer": "libpostal"
    },
```
my pelias.api service is stopped:
<details> 
  <summary>Error: Could not locate the bindings file</summary>

```
Tra 14 14:36:32 i5-4570 systemd[1]: Stopped Pelias API server
Tra 14 14:36:32 i5-4570 systemd[1]: Started Pelias API server
Tra 14 14:36:33 i5-4570 npm[9354]: > pelias-api@0.0.0-semantic-release start /home/kradem/repos/pelias/api
Tra 14 14:36:33 i5-4570 npm[9354]: > node index.js
Tra 14 14:36:33 i5-4570 npm[9354]: loading libpostal data, this may take a few seconds...
Tra 14 14:36:33 i5-4570 npm[9354]: /home/kradem/repos/pelias/api/node_modules/pelias-text-analyzer/node_modules/node-postal/node_modules/bindings/bindings.js:91
Tra 14 14:36:33 i5-4570 npm[9354]:   throw err
Tra 14 14:36:33 i5-4570 npm[9354]:   ^
Tra 14 14:36:33 i5-4570 npm[9354]: Error: Could not locate the bindings file. Tried:
Tra 14 14:36:33 i5-4570 npm[9354]:  → /home/kradem/repos/pelias/api/node_modules/pelias-text-analyzer/node_modules/node-postal/build/expand.node
Tra 14 14:36:33 i5-4570 npm[9354]:  → /home/kradem/repos/pelias/api/node_modules/pelias-text-analyzer/node_modules/node-postal/build/Debug/expand.node
Tra 14 14:36:33 i5-4570 npm[9354]:  → /home/kradem/repos/pelias/api/node_modules/pelias-text-analyzer/node_modules/node-postal/build/Release/expand.node
Tra 14 14:36:33 i5-4570 npm[9354]:  → /home/kradem/repos/pelias/api/node_modules/pelias-text-analyzer/node_modules/node-postal/out/Debug/expand.node
Tra 14 14:36:33 i5-4570 npm[9354]:  → /home/kradem/repos/pelias/api/node_modules/pelias-text-analyzer/node_modules/node-postal/Debug/expand.node
Tra 14 14:36:33 i5-4570 npm[9354]:  → /home/kradem/repos/pelias/api/node_modules/pelias-text-analyzer/node_modules/node-postal/out/Release/expand.node
Tra 14 14:36:33 i5-4570 npm[9354]:  → /home/kradem/repos/pelias/api/node_modules/pelias-text-analyzer/node_modules/node-postal/Release/expand.node
Tra 14 14:36:33 i5-4570 npm[9354]:  → /home/kradem/repos/pelias/api/node_modules/pelias-text-analyzer/node_modules/node-postal/build/default/expand.node
Tra 14 14:36:33 i5-4570 npm[9354]:  → /home/kradem/repos/pelias/api/node_modules/pelias-text-analyzer/node_modules/node-postal/compiled/4.8.2/linux/x64/expand.node
Tra 14 14:36:33 i5-4570 npm[9354]:     at bindings (/home/kradem/repos/pelias/api/node_modules/pelias-text-analyzer/node_modules/node-postal/node_modules/bindings/bindings.js:88:9)
Tra 14 14:36:33 i5-4570 npm[9354]:     at Object.<anonymous> (/home/kradem/repos/pelias/api/node_modules/pelias-text-analyzer/node_modules/node-postal/index.js:3:32)
Tra 14 14:36:33 i5-4570 npm[9354]:     at Module._compile (module.js:409:26)
Tra 14 14:36:33 i5-4570 npm[9354]:     at Object.Module._extensions..js (module.js:416:10)
Tra 14 14:36:33 i5-4570 npm[9354]:     at Module.load (module.js:343:32)
Tra 14 14:36:33 i5-4570 npm[9354]:     at Function.Module._load (module.js:300:12)
Tra 14 14:36:33 i5-4570 npm[9354]:     at Module.require (module.js:353:17)
Tra 14 14:36:33 i5-4570 npm[9354]:     at require (internal/module.js:12:17)
Tra 14 14:36:33 i5-4570 npm[9354]:     at Object.<anonymous> (/home/kradem/repos/pelias/api/node_modules/pelias-text-analyzer/index.js:11:18)
Tra 14 14:36:33 i5-4570 npm[9354]:     at Module._compile (module.js:409:26)
Tra 14 14:36:33 i5-4570 npm[9354]: npm ERR! Linux 4.4.0-72-generic
Tra 14 14:36:33 i5-4570 npm[9354]: npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
Tra 14 14:36:33 i5-4570 npm[9354]: npm ERR! node v4.8.2
Tra 14 14:36:33 i5-4570 npm[9354]: npm ERR! npm  v2.15.11
Tra 14 14:36:33 i5-4570 npm[9354]: npm ERR! code ELIFECYCLE
Tra 14 14:36:33 i5-4570 npm[9354]: npm ERR! pelias-api@0.0.0-semantic-release start: `node index.js`
Tra 14 14:36:33 i5-4570 npm[9354]: npm ERR! Exit status 1
Tra 14 14:36:33 i5-4570 npm[9354]: npm ERR!
Tra 14 14:36:33 i5-4570 npm[9354]: npm ERR! Failed at the pelias-api@0.0.0-semantic-release start script 'node index.js'.
Tra 14 14:36:33 i5-4570 npm[9354]: npm ERR! This is most likely a problem with the pelias-api package,
Tra 14 14:36:33 i5-4570 npm[9354]: npm ERR! not with npm itself.
Tra 14 14:36:33 i5-4570 npm[9354]: npm ERR! Tell the author that this fails on your system:
Tra 14 14:36:33 i5-4570 npm[9354]: npm ERR!     node index.js
Tra 14 14:36:33 i5-4570 npm[9354]: npm ERR! You can get information on how to open an issue for this project with:
Tra 14 14:36:33 i5-4570 npm[9354]: npm ERR!     npm bugs pelias-api
Tra 14 14:36:33 i5-4570 npm[9354]: npm ERR! Or if that isn't available, you can get their info via:
Tra 14 14:36:33 i5-4570 npm[9354]: npm ERR!
Tra 14 14:36:33 i5-4570 npm[9354]: npm ERR!     npm owner ls pelias-api
Tra 14 14:36:33 i5-4570 npm[9354]: npm ERR! There is likely additional logging output above.
Tra 14 14:36:33 i5-4570 npm[9354]: npm ERR! Please include the following file with any support request:
Tra 14 14:36:33 i5-4570 npm[9354]: npm ERR!     /home/kradem/repos/pelias/api/npm-debug.log
Tra 14 14:36:33 i5-4570 systemd[1]: pelias.service: Main process exited, code=exited, status=1/FAILURE
Tra 14 14:36:33 i5-4570 systemd[1]: pelias.service: Unit entered failed state.
Tra 14 14:36:33 i5-4570 systemd[1]: pelias.service: Failed with result 'exit-code'.
```

</details>

<br>
Also, libpostal's tests bring no errors:
<details> 
  <summary>make check</summary>

```
Making check in src
make[1]: Entering directory '/home/kradem/repos/libpostal/src'
./libpostal_data download all /media/data/resources/libpostal
Checking for new libpostal data file...
libpostal data file up to date
Checking for new libpostal parser data file...
libpostal parser data file up to date
Checking for new libpostal language classifier data file...
libpostal language classifier data file up to date
make[1]: Leaving directory '/home/kradem/repos/libpostal/src'
Making check in test
make[1]: Entering directory '/home/kradem/repos/libpostal/test'
make  check-TESTS
make[2]: Entering directory '/home/kradem/repos/libpostal/test'
make[3]: Entering directory '/home/kradem/repos/libpostal/test'
PASS: test_libpostal
============================================================================
Testsuite summary for libpostal 1.0.0
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[3]: Leaving directory '/home/kradem/repos/libpostal/test'
make[2]: Leaving directory '/home/kradem/repos/libpostal/test'
make[1]: Leaving directory '/home/kradem/repos/libpostal/test'
make[1]: Entering directory '/home/kradem/repos/libpostal'
make[1]: Leaving directory '/home/kradem/repos/libpostal'
```

</details>

<br>
I'm sorry I haven't marked my last successful build, but those repositories (both all pelias' and libpostal) have been updated regularly last few months and I have not had problems with this configuration. I suppose my last successful build was some 2 or 3 weeks ago.

<details> 
  <summary>System</summary>

```
$ node --version
v4.8.2
$ npm --version
2.15.11
$ uname -a
Linux ... 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ curl -XGET 'localhost:9200'
{
  "name" : "Tiger Shark",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "o3A-Zw2pRUaVttcM5280lQ",
  "version" : {
    "number" : "2.4.4",
    "build_hash" : "fcbb46dfd45562a9cf00c604b30849a6dec6b017",
    "build_timestamp" : "2017-01-03T11:33:16Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.2"
  },
  "tagline" : "You Know, for Search"
}
```

</details>

**Comment by orangejulius** [comment]
Hey @kradem,
Thanks for writing a very detailed summary of the issue. Libpostal recently published a new release that is incompatible with [node-postal](https://www.npmjs.com/package/node-postal)(the libpostal bindings module) version 0.3.0. A new version, 1.0.0 has been released that _is_compatible. We're still testing this release so we haven't updated the package version yet.

You have two options:
1. Upgrade to node-postal 1.0.0 and get the latest libpostal changes. By all accounts its likely to be much better, and we plan to switch to it soon.
2. Stick with an older version of libpostal. The current revision we know works is https://github.com/openvenues/libpostal/commit/14fa8a08c0ce66016268c0099ff11d7b2671c009. It's quite old though.

If you do opt for option one please let us know how it goes! We do plan to upgrade very soon so it's the choice I would recommend.

**Comment by kradem** [comment]
Hey @orangejulius\!

Thank you very much for your quick response.

I'd go with the new version as that has been the rule of thumb for all my project's dependencies - at least until I reach production! For example, I'm having my finger on the trigger [for this](https://github.com/pelias/pelias/issues/461#issuecomment-282107762) a long time ago. :)

I'm here with a report after afterward,

best regards!

**Comment by kradem** [comment]
I was following instructions from https://www.npmjs.com/package/node-postal and solved the issue with:
`~/repos/pelias/api/node_modules/pelias-text-analyzer/node_modules$ npm install openvenues/node-postal`

Now `package.json` in node-postal subdirectory lists:

```
  "name": "node-postal",
  "version": "1.0.0",
...
  "_id": "node-postal@1.0.0",
...
  "_from": "openvenues/node-postal",  

```
and it works just fine!

Thank you very much!

**Comment by orangejulius** [comment]
Hey @kradem, as of https://github.com/pelias/api/pull/858 node-postal 1.0.0 is supported out of the box, so everything should work for you on a clean master/staging/production branch. If there are any other issues let us know!

**Comment by Binternet** [comment]
@orangejulius I've just checked out `production` branch on the `api` repo, ran `npm install` and faced the same error. my `libpostal` is running in a docker container, maybe thats the issue?
Anyway I just tried @kradem solution and it seems to be working but i think that `libpostal` is now running on the instance itself and not the in the docker container.
